name: spin_http
description: A new Flutter FFI plugin project.
version: 0.0.1
homepage: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  meta: ^1.9.1
  ffi: ^2.0.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^6.1.2
  lints: ^2.0.1
  freezed: ^2.3.2