name: just_dart
description: Just a minimalist "Hello world" server build in Dart.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/iapicca/spinda

environment:
  sdk: '>=2.19.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
